<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Shared trait for restoring the CCH fixture course from the MBZ backup.
 *
 * Usage: use course_fixture_helper; inside a testcase, then call
 * $this->restore_cch_fixture_course() in setUp() or at the start of a test.
 *
 * @package    local_coursectrl
 * @copyright  2026 Ralf Erlebach
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_coursectrl\tests;

/**
 * Provides restore_cch_fixture_course() for integration tests that need
 * the full CCH-FIXTURE-2026 course with all activities, groups, and availability
 * conditions as generated by the fixture generator.
 *
 * The restored course id is stored in $this->fixturecourse (stdClass).
 * A fresh restore is performed for each test that calls the method.
 */
trait course_fixture_helper {
    /** @var \stdClass Restored course record, set by restore_cch_fixture_course(). */
    protected \stdClass $fixturecourse;

    /** @var int Category id used for the restored course. */
    private int $fixturecategoryid = 1;

    /**
     * Restore the CCH fixture MBZ into a fresh course and populate
     * $this->fixturecourse with the resulting course record.
     *
     * Must be called inside a test that has already called resetAfterTest().
     *
     * @return void
     */
    protected function restore_cch_fixture_course(): void {
        global $CFG, $DB, $USER;

        require_once($CFG->dirroot . '/backup/util/includes/restore_includes.php');

        // Ensure we have a valid admin user session.
        if (!isset($USER->id) || !$USER->id) {
            $admin = get_admin();
            \core\session\manager::set_user($admin);
        }

        $mbzpath = __DIR__ . '/cch_fixture_2026.mbz';
        if (!is_readable($mbzpath)) {
            $this->markTestSkipped("CCH fixture MBZ not found at $mbzpath — skipping integration test.");
        }

        // Extract the MBZ into a temporary directory.
        $tmpdir = make_request_directory();
        $packer = get_file_packer('application/vnd.moodle.backup');
        $packer->extract_to_pathname($mbzpath, $tmpdir);

        // Restore into a new course in the default category.
        $restoretarget = \backup::TARGET_NEW_COURSE;
        $controller = new \restore_controller(
            basename($tmpdir),
            0,
            \backup::INTERACTIVE_NO,
            \backup::MODE_GENERAL,
            $USER->id,
            $restoretarget
        );

        // Set the target category.
        $controller->get_plan()->get_setting('course_id')->set_value(0);
        $controller->get_plan()->get_setting('overwrite_conf')->set_value(true);

        $controller->execute_precheck();
        $controller->execute_plan();

        $courseid = (int) $controller->get_courseid();
        $controller->destroy();

        $this->fixturecourse = $DB->get_record('course', ['id' => $courseid], '*', \MUST_EXIST);
    }

    /**
     * Return all cmids for the restored fixture course, keyed by activity name.
     *
     * @return array<string, int> name → cmid
     */
    protected function get_fixture_cmids_by_name(): array {
        global $DB;
        if (!isset($this->fixturecourse)) {
            $this->fail('restore_cch_fixture_course() must be called first.');
        }
        $modinfo = get_fast_modinfo($this->fixturecourse->id);
        $map = [];
        foreach ($modinfo->get_cms() as $cm) {
            $map[$cm->name] = (int) $cm->id;
        }
        return $map;
    }

    /**
     * Return the first cmid whose name contains the given prefix.
     *
     * @param string $prefix Name prefix (e.g. '[OK] Aufgabe 1').
     * @return int cmid
     */
    protected function get_fixture_cmid(string $prefix): int {
        foreach ($this->get_fixture_cmids_by_name() as $name => $cmid) {
            if (str_starts_with($name, $prefix)) {
                return $cmid;
            }
        }
        $this->fail("No CM found with name starting '$prefix' in fixture course.");
    }
}
